### PR TITLE
fix: properly handle termination of Snaps while executing

### LINKED ISSUE #2300: Certain Snaps failing to terminate properly when being uninstalled
`Snap "local:http://localhost:8080" runtime data not found`

### PR DESCRIPTION
**Pull request by FrederikBolding**
Fixes an issue where terminating a Snap that is currently executing (e.g. when removing it) would cause unexpected errors to be thrown.

Fixes #2300

### CODE REVIEW

File: packages/snaps-controllers/src/snaps/Timer.ts [hunk 1]
```diff
@@ -52,6 +52,19 @@ export class Timer {
...
 
+  /**
+   * Marks the timer as finished prematurely and triggers the callback.
+   *
+   * @throws {@link Error}. If it wasn't running or paused.
+   */
+  finish() {
+    assert(
+      this.status !== 'finished',
+      new Error('Tried to finish a finished Timer'),
```
Comment (Mrtenz) [inline packages/snaps-controllers/src/snaps/Timer.ts:63]:
```suggestion
      new Error('Tried to finish a finished Timer.'),
```

**Review by Mrtenz — APPROVED** [review]
